import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export const translations = {
  en: {
    // Navigation
    'nav.shops': 'Shops',
    'nav.compare': 'Compare',
    'nav.khata': 'My Khata',
    'nav.orders': 'All Orders',
    'nav.more': 'More',
    'nav.pos': 'POS',
    'nav.items': 'Catalog',
    'nav.staff': 'Staff',
    'nav.analytics': 'Analytics',

    'POS': 'POS',
    'My Khata': 'My Khata',
    'All Orders': 'All Orders',
    'Analytics': 'Analytics',
    'More': 'More',
    'Shops': 'Shops',
    'Compare': 'Compare',
    'Catalog': 'Catalog',

    // Common Actions & Labels
    'common.save': 'Save Changes',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.total': 'Total',
    'common.logout': 'Log Out',
    'common.back': 'Back',
    'common.phone': 'Mobile Phone',
    'common.city': 'City / Location',
    'common.address': 'Address',
    'common.name': 'Full Name',

    // More Tab & Account
    'more.title': 'Account & Settings',
    'more.subtitle': 'Manage language, profile, PIN & session',
    'more.langCardTitle': 'Choose Language',
    'more.langCardSubtitle': 'Select your preferred language for the application',
    'more.english': 'English',
    'more.hindi': 'हिंदी (Hindi)',
    'more.profileOverview': 'Personal & Delivery Details',
    'more.securityLock': 'Security PIN & Access',
    'more.changePin': 'Change 4-Digit Security PIN',
    'more.changePassword': 'Change Account Password',
    'more.legalPrivacy': 'Legal & Privacy',
    'more.privacyPolicy': 'Privacy Policy',
    'more.termsConditions': 'Terms & Conditions',
    'more.deleteAccount': 'Account Deletion Request',
    'more.storeTitle': 'Store Operations & Settings',
    'more.storeStatus': 'Store Status',
    'more.shopOpen': '🟢 Shop is OPEN',
    'more.shopClosed': '🔴 Shop is CLOSED',
    'more.openShopBtn': 'Open Shop',
    'more.closeShopBtn': 'Close Shop',
    'more.editStoreProfile': 'Edit Store Profile',
    'more.shortId': 'SHORT ID',

    // Customer specific
    'customer.searchPlaceholder': 'Search products, shops or brands...',
    'customer.exploreTitle': 'Local Stores in Your City',
    'customer.khataTitle': 'Customer Khata (Digital Udhar)',
    'customer.ordersTitle': 'Order History & Status',
    
    // Shopkeeper specific
    'shop.posTitle': 'Point of Sale (POS)',
    'shop.khataTitle': 'Customer Udhar Khata',
    'shop.ordersTitle': 'Customer Online Orders',
    'shop.analyticsTitle': 'Sales & Revenue Analytics',
    'shop.productsTitle': 'Product Catalog',
    'shop.staffTitle': 'Store Cashiers & Staff',
    'Call': 'Call',
    'No Phone Linked': 'No Phone Linked',
    'App Account': 'App Account',
    'No Phone Number': 'No Phone Number',
    'A valid phone number is not available for this customer.': 'A valid phone number is not available for this customer.',
  },
  hi: {
    // Navigation
    'nav.shops': 'दुकानें',
    'nav.compare': 'मूल्य तुलना',
    'nav.khata': 'मेरा खाता',
    'nav.orders': 'सभी ऑर्डर्स',
    'nav.more': 'अधिक',
    'nav.pos': 'बिलिंग (POS)',
    'nav.items': 'उत्पाद सूची',
    'nav.staff': 'कर्मचारी',
    'nav.analytics': 'बिक्री रिपोर्ट',

    'POS': 'बिलिंग (POS)',
    'My Khata': 'मेरा खाता',
    'All Orders': 'सभी ऑर्डर्स',
    'Analytics': 'बिक्री रिपोर्ट',
    'More': 'अधिक',
    'Shops': 'दुकानें',
    'Compare': 'मूल्य तुलना',
    'Catalog': 'कैटलॉग',

    // Common Actions & Labels
    'common.save': 'बदलाव सहेजें',
    'common.saving': 'सहेज रहे हैं...',
    'common.cancel': 'रद्द करें',
    'common.close': 'बंद करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.search': 'खोजें',
    'common.total': 'कुल राशि',
    'common.logout': 'लॉग आउट',
    'common.back': 'वापस जाएं',
    'common.phone': 'मोबाइल नंबर',
    'common.city': 'शहर / स्थान',
    'common.address': 'डिलीवरी पता',
    'common.name': 'पूरा नाम',

    // More Tab & Account
    'more.title': 'खाता और सेटिंग्स',
    'more.subtitle': 'भाषा, प्रोफ़ाइल, सुरक्षा पिन और सेटिंग्स प्रबंधित करें',
    'more.langCardTitle': 'भाषा चुनें',
    'more.langCardSubtitle': 'एप्लिकेशन के लिए अपनी पसंदीदा भाषा चुनें',
    'more.english': 'English',
    'more.hindi': 'हिंदी (Hindi)',
    'more.profileOverview': 'व्यक्तिगत और डिलीवरी विवरण',
    'more.securityLock': 'सुरक्षा पिन और एक्सेस',
    'more.changePin': '4-अंकों का सुरक्षा पिन बदलें',
    'more.changePassword': 'अकाउंट पासवर्ड बदलें',
    'more.legalPrivacy': 'कानूनी व नीतियां',
    'more.privacyPolicy': 'गोपनीयता नीति (Privacy Policy)',
    'more.termsConditions': 'नियम व शर्तें (Terms & Conditions)',
    'more.deleteAccount': 'खाता हटाने का अनुरोध',
    'more.storeTitle': 'दुकान संचालन और सेटिंग्स',
    'more.storeStatus': 'दुकान की स्थिति',
    'more.shopOpen': '🟢 दुकान खुली है',
    'more.shopClosed': '🔴 दुकान बंद है',
    'more.openShopBtn': 'दुकान खोलें',
    'more.closeShopBtn': 'दुकान बंद करें',
    'more.editStoreProfile': 'दुकान प्रोफ़ाइल संपादित करें',
    'more.shortId': 'शॉर्ट आईडी (ID)',

    // Language Card Direct Lookups
    'Choose Language / भाषा चुनें': 'भाषा चुनें',
    'Choose Language': 'भाषा चुनें',
    'Select your preferred language for the application': 'एप्लिकेशन के लिए अपनी पसंदीदा भाषा चुनें',
    'Select your preferred language': 'अपनी पसंदीदा भाषा चुनें',
    'English': 'English',
    'हिंदी (Hindi)': 'हिंदी (Hindi)',

    // Header & Subtitles
    'Point of Sale & Smart Billing': 'स्मार्ट पीओएस व बिलिंग',
    'Incoming Orders & Live Packing': 'आने वाले ऑर्डर्स और लाइव पैकिंग',
    'Customer Khata & Udhar Ledger': 'ग्राहक खाता और उधार बहीखाता',
    'Sales & Revenue Performance': 'बिक्री और राजस्व रिपोर्ट',
    'Account & Settings': 'खाता और सेटिंग्स',
    'Manage language, profile, PIN & session': 'भाषा, प्रोफ़ाइल, सुरक्षा पिन और सेटिंग्स प्रबंधित करें',
    'More Options': 'अन्य विकल्प',
    'Store Settings & Operations': 'दुकान सेटिंग्स व संचालन',
    'Manage Items': 'उत्पाद प्रबंधन',
    'Product Catalog & Pricing': 'सामान सूची व मूल्य',
    'Cashiers & Store Staff': 'कैशियर व दुकान कर्मचारी',
    'Edit Shop Details': 'दुकान विवरण संपादित करें',
    'Address, Timings & Info': 'पता, समय व जानकारी',
    'Security PIN': 'सुरक्षा पिन',
    'Change 4-Digit Lock PIN': '4-अंकों का लॉक पिन बदलें',

    // More Screen Menu Items
    'Items & Price Catalog': 'सामान व मूल्य सूची (कैटलॉग)',
    'Items': 'सामान',
    'Staff Management': 'कर्मचारी प्रबंधन',
    'Profile & Settings': 'प्रोफ़ाइल व सेटिंग्स',
    'Account Password': 'खाता पासवर्ड',
    'Contact Customer Care': 'कस्टमर केयर से संपर्क करें',
    'Call 7323809242 for instant help': 'तुरंत सहायता के लिए 7323809242 पर कॉल करें',
    'Privacy Policy': 'गोपनीयता नीति (Privacy Policy)',
    'Terms & Conditions': 'नियम व शर्तें (Terms & Conditions)',
    'Account Deletion Request': 'खाता हटाने का अनुरोध',
    'Log Out': 'लॉग आउट',
    'Are you sure you want to log out?': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'Store Status': 'दुकान की स्थिति',
    'Store Status:': 'दुकान की स्थिति:',
    'OPEN': 'खुली है (OPEN)',
    'CLOSED': 'बंद है (CLOSED)',
    'Open Shop': 'दुकान खोलें',
    'Close Shop': 'दुकान बंद करें',
    'Shop Owner': 'दुकान मालिक',
    'Cashier': 'कैशियर / स्टाफ',
    'Edit': 'संपादित करें',
    'Change 4-Digit Security PIN': '4-अंकों का सुरक्षा पिन बदलें',
    'Current 4-Digit PIN': 'वर्तमान 4-अंकों का पिन',
    'New 4-Digit PIN': 'नया 4-अंकों का पिन',
    'Confirm New PIN': 'नया पिन पुनः दर्ज करें',
    'Save Changes': 'बदलाव सहेजें',
    'Saving...': 'सहेज रहे हैं...',
    'Cancel': 'रद्द करें',
    'Close': 'बंद करें',
    'Back': 'वापस',
    '← Back to More': '← वापस मेन्यू पर',
    'Active Catalog': 'सक्रिय उत्पाद सूची',
    'Add Item': 'नया सामान जोड़ें',
    'Search catalog items...': 'उत्पाद खोजें...',
    'No Items Found': 'कोई उत्पाद नहीं मिला',
    'Staff & Cashier Management': 'स्टाफ और कैशियर प्रबंधन',
    'Invite Cashier': 'कैशियर जोड़ें',
    'Enter Mobile Number': 'मोबाइल नंबर दर्ज करें',
    'Send Invite': 'आमंत्रण भेजें',
    'Current Staff': 'वर्तमान कर्मचारी',
    'Active Cashier': 'सक्रिय कैशियर',
    'Invite Pending': 'आमंत्रण लंबित',
    'No Staff Members': 'कोई कर्मचारी नहीं',
    'Invite cashiers using the form above to help manage your POS billing.': 'बिलिंग में सहायता के लिए ऊपर दिए गए फॉर्म से कैशियर जोड़ें।',
    'Enter customer\'s Short ID or Phone number to add them as a cashier.': 'कैशियर बनाने के लिए ग्राहक का शॉर्ट आईडी या फोन नंबर दर्ज करें।',
    'Customer Short ID or Phone': 'ग्राहक शॉर्ट आईडी या फोन',
    'Invite': 'आमंत्रण भेजें',
    'You are logged in as Cashier. Only the shop owner can invite or remove staff.': 'आप कैशियर के रूप में लॉग इन हैं। केवल दुकान मालिक ही कर्मचारी जोड़ या हटा सकते हैं।',
    'Edit Shop Details & Information': 'दुकान का विवरण और जानकारी बदलें',
    'View-Only Mode: You are logged in as Cashier. Only the shop owner can modify store details.': 'केवल देखने का मोड: आप कैशियर के रूप में लॉग इन हैं। केवल दुकान मालिक ही विवरण बदल सकते हैं।',
    'Shop Name': 'दुकान का नाम',
    'Contact Phone': 'संपर्क फोन',
    'Shop City / Region': 'दुकान का शहर / क्षेत्र',
    'Locked (SuperAdmin only)': 'लॉक है (केवल SuperAdmin)',
    'Store city is locked to protect orders & billing records. Contact SuperAdmin (7323809242) to request a city transfer.': 'ऑर्डर और बिलिंग रिकॉर्ड की सुरक्षा के लिए दुकान का शहर लॉक है। बदलने के लिए सुपर एडमिन (7323809242) से संपर्क करें।',
    'Shop Address': 'दुकान का पता',
    'Operating Timings': 'खुलने का समय',
    'Save Shop Changes': 'दुकान के बदलाव सहेजें',
    'Search items by name...': 'नाम से उत्पाद खोजें...',
    'Tap "Add Item" above to add items to your catalog.': 'कैटलॉग में उत्पाद जोड़ने के लिए ऊपर "नया सामान जोड़ें" दबाएं।',
    'Update Security PIN': 'सुरक्षा पिन बदलें',
    'Store Profile': 'दुकान प्रोफ़ाइल',
    'Store Details': 'दुकान का विवरण',
    'Store Name': 'दुकान का नाम',
    'Store Address': 'दुकान का पता',
    'City / Location': 'शहर / स्थान',
    'Mobile Phone': 'मोबाइल नंबर',
    'Full Name': 'पूरा नाम',

    // POS Screen
    'Customer Account': 'ग्राहक खाता',
    'Enter Phone or Name (Optional)': 'मोबाइल नंबर या नाम दर्ज करें (वैकल्पिक)',
    'Search Customer': 'ग्राहक खोजें',
    'Please enter a phone number or name to search.': 'कृपया खोजने के लिए फ़ोन नंबर या नाम दर्ज करें।',
    'Customer Found': 'ग्राहक मिल गया',
    'Not Found': 'नहीं मिला',
    'No customer found with that phone or name.': 'इस फ़ोन नंबर या नाम से कोई ग्राहक नहीं मिला।',
    'Search products (e.g. Milk, Rice)...': 'सामान खोजें (जैसे दूध, चावल, तेल)...',
    'Unable to load products from server': 'सर्वर से उत्पाद लोड नहीं हो सके',
    'Please check your connection and tap to retry': 'कृपया इंटरनेट जांचें और पुनः प्रयास करें',
    'Refresh Products': 'सामान पुनः लोड करें',
    'Clear Cart': 'कार्ट खाली करें',
    'Cart': 'कार्ट',
    'View Cart': 'कार्ट देखें',
    'Item in Cart': 'सामान कार्ट में',
    'Items in Cart': 'सामान कार्ट में',
    'Order Cart': 'ऑर्डर कार्ट',
    'Clear All': 'सब हटाएं',
    'Clear': 'हटाएं',
    'Billing Customer': 'बिलिंग ग्राहक',
    'Walk-in / Cash Customer': 'नकद ग्राहक (Walk-in)',
    'Items in Bill': 'बिल का सामान',
    'Subtotal': 'उप-योग (Subtotal)',
    'Discount': 'छूट (Discount)',
    'Discount (Flat ₹)': 'छूट (सीधी ₹ में)',
    'Total': 'कुल राशि',
    'TOTAL PAYABLE': 'कुल देय राशि',
    'Payment Method': 'भुगतान का माध्यम',
    'Collect Cash': 'नकद भुगतान (Cash)',
    'Online Payment': 'ऑनलाइन भुगतान (Online/UPI)',
    'Add to Khata': 'खाता में जोड़ें (उधार)',
    'Checkout': 'बिल बनाएं',
    'Complete Bill': 'बिल पूरा करें',
    'No matching products': 'कोई सामान नहीं मिला',
    'No products in store yet': 'दुकान में अभी कोई सामान नहीं है',
    'Add products from Inventory or More tab': 'इन्वेंटरी या मेन्यू से सामान जोड़ें',
    'Try searching with another keyword': 'किसी अन्य कीवर्ड से खोजें',
    'Clear Search': 'खोज हटाएं',
    'Quick Add': 'तुरंत जोड़ें',
    'Add Custom Item': 'नया सामान जोड़ें',
    'Quantity': 'मात्रा',
    'Price': 'मूल्य',
    'Item Name': 'सामान का नाम',
    'Refreshing store catalog...': 'कैटलॉग अपडेट हो रहा है...',

    // Orders Screen
    'Search order #, customer, phone...': 'ऑर्डर नंबर, ग्राहक या फोन से खोजें...',
    'PENDING': 'लंबित (Pending)',
    'PACKING': 'पैकिंग जारी (Packing)',
    'READY': 'तैयार (Ready)',
    'COMPLETED': 'पूर्ण (Completed)',
    'CANCELLED': 'रद्द (Cancelled)',
    'All Dates': 'सभी तारीखें',
    'Today': 'आज',
    'Yesterday': 'कल',
    'Older (>24h)': 'पुराने (>24 घंटे)',
    'All Status': 'सभी स्थिति',
    'Pending': 'लंबित (Pending)',
    'Packing': 'पैकिंग जारी (Packing)',
    'Ready': 'तैयार (Ready)',
    'Completed': 'पूर्ण (Completed)',
    'Cancelled': 'रद्द (Cancelled)',
    'Active Orders (<24h)': 'सक्रिय ऑर्डर्स (<24 घंटे)',
    'Past Orders (>24h & Finalized)': 'पुराने ऑर्डर्स (पूर्ण व समाप्त)',
    'Orders older than 24h or collected/cancelled': '24 घंटे से पुराने या समाप्त ऑर्डर्स',
    'Order Details': 'ऑर्डर विवरण',
    'Decline': 'अस्वीकार करें',
    'Order': 'ऑर्डर',
    'Order #': 'ऑर्डर #',
    'Past 24h': 'पिछले 24 घंटे',
    'View Order': 'ऑर्डर देखें',
    'Accept & Pack': 'स्वीकार करें और पैक करें',
    'Mark Unavailable': 'हटाएं (स्टॉक खत्म)',
    'Mark Available': 'वापस जोड़ें',
    'UNAVAILABLE': 'अनुपलब्ध',
    'Restore': 'वापस जोड़ें',
    'Mark Out': 'हटाएं (स्टॉक खत्म)',
    'Total Payable:': 'कुल देय राशि:',
    'Total Payable': 'कुल देय राशि',
    'Ready (Waiting Customer)': 'तैयार (ग्राहक की प्रतीक्षा)',
    'ORDER COMPLETED': 'ऑर्डर पूर्ण',
    'Order Completed': 'ऑर्डर पूर्ण',
    'Customer Collected': 'ग्राहक द्वारा प्राप्त',
    'Marked Not Collected': 'प्राप्त नहीं किया गया',
    'Cancelled by Customer': 'ग्राहक द्वारा रद्द',
    'Auto-cancelled (Expired)': 'स्वतः रद्द (समय समाप्त)',
    'Order Ready for Pickup': 'ऑर्डर लेने के लिए तैयार है',
    'No payment request sent yet.': 'अभी तक भुगतान अनुरोध नहीं भेजा गया।',
    'Get Payment': 'भुगतान मांगें',
    'Payment Requested': 'भुगतान अनुरोध भेजा गया',
    'Amount': 'राशि',
    'Mode': 'माध्यम',
    'Cash': 'नकद (Cash)',
    'Online': 'ऑनलाइन (UPI)',
    'Online / UPI': 'ऑनलाइन (UPI)',
    'Add to Book': 'खाता में दर्ज (उधार)',
    'Enter Customer OTP': 'ग्राहक का 4-अंकों का ओटीपी दर्ज करें',
    'Verify OTP & Complete': 'ओटीपी सत्यापित करें और पूरा करें',
    'Order Completed & Handed Over': 'ऑर्डर पूरा हुआ और सौंप दिया गया',
    '✓ Order Completed & Handed Over': '✓ ऑर्डर पूरा हुआ और सौंप दिया गया',
    'Customer verified via OTP. Sale recorded in ledger.': 'ग्राहक ओटीपी सत्यापित। बिक्री बहीखाते में दर्ज।',
    'Order finalized and collected by customer. (Locked)': 'ऑर्डर पूरा हुआ और ग्राहक द्वारा प्राप्त कर लिया गया।',
    'Customer marked as not collected. (Locked)': 'ग्राहक ने सामान नहीं लिया।',
    'Customer cancelled / took back this order. (Locked)': 'ग्राहक ने यह ऑर्डर रद्द कर दिया।',
    'Accept Order': 'ऑर्डर स्वीकार करें',
    'Decline Order': 'ऑर्डर अस्वीकार करें',
    'Estimated Packing Time': 'अनुमानित पैकिंग समय',
    'Minutes': 'मिनट',
    'Reason for declining': 'अस्वीकार करने का कारण',
    'Send Request': 'अनुरोध भेजें',
    'Confirm Request': 'पुष्टि करें',

    // Khata Screen
    'Khata & Udhar Ledger': 'खाता और उधार बहीखाता',
    'Customer Khata Timeline': 'ग्राहक खाता और लेन-देन',
    'Back to List': 'वापस सूची पर',
    'Total Outstanding Credit': 'कुल बकाया उधार (मार्केट में)',
    'Total Outstanding Khata': 'मार्केट में कुल बकाया उधार',
    'Enrolled Customers': 'पंजीकृत ग्राहक',
    'You will collect': 'आपको लेना है',
    'You will give': 'आपको देना है',
    'Search customers by name or phone...': 'ग्राहक का नाम या फोन नंबर खोजें...',
    'Search by customer phone or name...': 'ग्राहक का नाम या फोन नंबर खोजें...',
    'Customers': 'ग्राहक',
    'Add Customer': 'नया ग्राहक जोड़ें',
    'Add': 'जोड़ें',
    'All': 'सभी',
    'Highest': 'अधिकतम उधार',
    'Lowest': 'न्यूनतम उधार',
    'No Due': 'कोई बकाया नहीं',
    'Filter Khata By': 'खाता फ़िल्टर करें',
    'Tap to collapse past orders': 'पुराने ऑर्डर समेटने के लिए दबाएं',
    'Tap to view grouped past orders': 'पुराने ऑर्डर देखने के लिए दबाएं',
    'Search GI SHOP Account': 'GI SHOP खाता खोजें',
    'Due': 'बकाया',
    'Remind': 'याद दिलाएं',
    'Settle': 'हिसाब करें',
    'Settle Due': 'हिसाब चुकता करें',
    'Give Credit (Udhar)': 'उधार दिया (-)',
    'Got Payment (Jama)': 'जमा मिला (+)',
    'Give Udhar': 'उधार दिया (-)',
    'Receive Payment': 'भुगतान मिला (+)',
    'Customer Ledger': 'ग्राहक बहीखाता',
    'Current Due': 'वर्तमान बकाया',
    'Ledger Timeline': 'लेन-देन इतिहास (टाइमलाइन)',
    'Payment Received': 'भुगतान प्राप्त हुआ',
    'Bill': 'बिल',
    'Balance:': 'बकाया:',
    'Balance': 'बकाया',
    'Terminate Relationship': 'ग्राहक खाता समाप्त करें',
    'All Customers': 'सभी ग्राहक',
    'Call': 'कॉल करें',
    'No Phone Linked': 'फ़ोन लिंक नहीं',
    'App Account': 'ऐप खाता',
    'No Phone Number': 'फ़ोन नंबर उपलब्ध नहीं',
    'A valid phone number is not available for this customer.': 'इस ग्राहक के लिए वैध फ़ोन नंबर उपलब्ध नहीं है।',
    'WhatsApp': 'व्हाट्सएप',
    'Send WhatsApp Reminder': 'व्हाट्सएप रिमाइंडर भेजें',
    'Transaction History': 'लेन-देन इतिहास',
    'No customers found': 'कोई ग्राहक नहीं मिला',
    'No Customers Found': 'कोई ग्राहक नहीं मिला',
    'Add your first customer to track udhar ledger.': 'उधार बहीखाता शुरू करने के लिए पहला ग्राहक जोड़ें।',
    'No transactions recorded yet.': 'अभी तक कोई लेन-देन दर्ज नहीं है।',
    'No transactions match selected date filter.': 'चुनी गई तारीख में कोई लेन-देन नहीं मिला।',
    'Due Date': 'अंतिम तारीख',
    'Notes / Bill Remarks': 'नोट्स / बिल विवरण',

    // Analytics Screen
    'Sales Analytics & Transactions': 'बिक्री एनालिटिक्स और लेन-देन',
    'Sales & Revenue Performance': 'बिक्री और राजस्व रिपोर्ट',
    'Today': 'आज',
    'Yesterday': 'कल',
    'This Week': 'इस सप्ताह',
    'This Month': 'इस महीने',
    'All Time': 'कुल समय',
    'Total Sales': 'कुल बिक्री',
    'Cash Sales': 'नकद बिक्री',
    'Khata (Credit)': 'खाता (उधार)',
    'Transactions': 'लेन-देन',
    'Sales Note': 'बिक्री नोट',
    'Add Note': 'नोट जोड़ें',
    'Edit Note': 'नोट बदलें',
    'Save Note': 'नोट सहेजें',
    'No Transactions Found': 'कोई लेन-देन नहीं मिला',
    'No note added': 'कोई नोट नहीं',
    'Memo Note': 'मेमो नोट',

    // Customer Side
    'Local Stores in Your City': 'आपके शहर की स्थानीय दुकानें',
    'Local Stores & Catalog': 'स्थानीय दुकानें व किराना सूची',
    'Smart Grocery Discovery': 'किराना खोजें और ऑर्डर करें',
    'City:': 'शहर:',
    'No shops found': 'कोई दुकान नहीं मिली',
    'View Catalog & Order →': 'कैटलॉग देखें और ऑर्डर करें →',
    'Search products, shops or brands...': 'दुकानें, किराना या सामान खोजें...',
    'Customer Khata (Digital Udhar)': 'डिजिटल उधार खाता (Khata)',
    'My Khata & Store Credits': 'मेरा खाता और उधार विवरण',
    'Order History & Status': 'ऑर्डर इतिहास और लाइव स्थिति',
    'Total Lifetime Purchases': 'कुल जीवनकाल खरीदारी',
    'Total Store Credit Due': 'दुकान का कुल बकाया उधार',
    'Enrolled Stores': 'पंजीकृत दुकानें',
    'with Due': 'उधार बाकी',
    'Stores': 'दुकानें',
    'No Khata Records Found': 'कोई खाता रिकॉर्ड नहीं मिला',
    'Explore Local Shops': 'स्थानीय दुकानें देखें',
    '+ New Order +': '+ नया ऑर्डर +',
    'Active Grocery Requests': 'सक्रिय किराना ऑर्डर्स',
    'Past Orders & Receipts': 'पुराने ऑर्डर्स और रसीदें',
    'Active': 'सक्रिय',
    'Total Outstanding Balance': 'कुल बकाया राशि',
    'Stores with Pending Khata': 'दुकानें जहाँ उधार बकाया है',
    'Active Udhar Stores': 'सक्रिय उधार दुकानें',
    'Due to Pay': 'देना बाकी',
    'No Due ✓': 'कोई बकाया नहीं ✓',
    'New Order +': 'नया ऑर्डर +',
    'View History →': 'इतिहास देखें →',
    'View Details →': 'विवरण देखें →',
    '← Back to All Stores': '← सभी दुकानों पर वापस',
    'Store Statement': 'दुकान का खाता विवरण',
    'Total Store Due': 'दुकान का कुल बकाया',
    'View Digital Receipt': 'डिजिटल रसीद देखें',
    'Account & Security': 'खाता और सुरक्षा',
    'Legal & Account Control': 'कानूनी व खाता नियंत्रण',
    'Session & Security': 'सत्र और सुरक्षा',
    'Switch Account / Log Out': 'खाता बदलें / लॉग आउट',
    'Edit Profile': 'प्रोफ़ाइल बदलें',
    'ID': 'आईडी',
    'Shop ID': 'दुकान आईडी',
    'Smart Billing & Khata': 'स्मार्ट बिलिंग और खाता',
    'No past orders or purchase receipts found.': 'कोई पुराना ऑर्डर या रसीद नहीं मिली।',
    'Loading your orders & receipts...': 'ऑर्डर्स और रसीदें लोड हो रही हैं...',
    'Acceptance Window:': 'स्वीकृति समय:',
    'Handover 4-Digit OTP': 'काउंटर पर 4-अंकों का ओटीपी बताएं',
    'Share this 4-digit code with shopkeeper at pickup counter': 'काउंटर पर यह 4-अंकों का कोड बताएं',
    '🎉 Your Order is Ready for Pickup!': '🎉 आपका ऑर्डर लेने के लिए तैयार है!',
    'Payment Mode:': 'भुगतान माध्यम:',
    'Amount:': 'राशि:',
    '✓ Order Picked Up & Completed': '✓ ऑर्डर प्राप्त हुआ और पूरा हुआ',
    'OTP verified. Items collected from shop.': 'ओटीपी सत्यापित। दुकान से सामान प्राप्त कर लिया गया।',
    'Cancel Order': 'ऑर्डर रद्द करें',
    'Are you sure you want to cancel this order?': 'क्या आप वाकई यह ऑर्डर रद्द करना चाहते हैं?',
    'Download Receipt (PDF)': 'रसीद डाउनलोड करें (PDF)',
    'Share Receipt': 'रसीद शेयर करें',
    'Receipt': 'दुकान रसीद',
    'Store Receipt': 'दुकान रसीद',
    'Rate': 'दर',
    'Qty': 'मात्रा',
    'Amount': 'राशि',
    'Thank you for shopping with us!': 'हमारे यहाँ खरीदारी करने के लिए धन्यवाद!',
  },
};

const STORAGE_KEY = '@gishop_language';

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
  isHindi: false,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((saved) => {
        if (saved === 'hi' || saved === 'en') {
          setLanguageState(saved);
        }
      })
      .catch(() => {});
  }, []);

  const setLanguage = async (newLang) => {
    const valid = newLang === 'hi' ? 'hi' : 'en';
    setLanguageState(valid);
    try {
      await AsyncStorage.setItem(STORAGE_KEY, valid);
    } catch (e) {}
  };

  const t = (key, fallback) => {
    if (key === undefined || key === null || key === '') return '';
    const langDict = translations[language] || translations.en;
    
    // 1. Direct dictionary match
    if (langDict[key] !== undefined) return langDict[key];

    // 2. Trimmed match
    const trimmed = typeof key === 'string' ? key.trim() : key;
    if (langDict[trimmed] !== undefined) return langDict[trimmed];

    // 3. Fallback to English dictionary if English mode or key is a dot key
    if (language === 'en') {
      const enDict = translations.en;
      if (enDict[key] !== undefined) return enDict[key];
      if (enDict[trimmed] !== undefined) return enDict[trimmed];
    }

    return fallback !== undefined ? fallback : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isHindi: language === 'hi' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
export const useLanguage = useTranslation;
export default LanguageContext;
